'use strict';

const mongoose = require('mongoose');
const crypto = require('crypto');

const partnerSchema = new mongoose.Schema(
  {
    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, unique: true },

    // ─── Profile ───────────────────────────────────────────────────────────
    businessName: { type: String, trim: true, maxlength: 100 },
    bio: { type: String, maxlength: 1000 },
    website: { type: String },
    socialHandles: {
      instagram: String,
      tiktok: String,
      youtube: String,
      twitter: String,
    },
    audienceSize: { type: Number, default: 0 },
    niche: {
      type: String,
      enum: ['wellness', 'fitness', 'lifestyle', 'nutrition', 'beauty', 'medical', 'other'],
    },

    // ─── Program Status ────────────────────────────────────────────────────
    status: {
      type: String,
      enum: ['pending', 'approved', 'suspended', 'rejected'],
      default: 'pending',
    },
    tier: {
      type: String,
      enum: ['alchemist', 'golden'],
      default: 'alchemist',
    },
    approvedAt: { type: Date, default: null },
    approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },

    // ─── Referral ──────────────────────────────────────────────────────────
    referralCode: { type: String, unique: true },
    referralLink: { type: String },
    utmSource: { type: String, default: 'partner' },

    // ─── Commission ────────────────────────────────────────────────────────
    commissionRate: {
      type: Number,
      default: parseFloat(process.env.PARTNER_COMMISSION_RATE || '0.15'),
    },
    commissionHistory: [
      {
        order: { type: mongoose.Schema.Types.ObjectId, ref: 'Order' },
        amount: Number,
        rate: Number,
        status: {
          type: String,
          enum: ['pending', 'paid', 'cancelled'],
          default: 'pending',
        },
        paidAt: { type: Date, default: null },
        createdAt: { type: Date, default: Date.now },
      },
    ],

    // ─── Aggregated Stats ──────────────────────────────────────────────────
    totalReferrals: { type: Number, default: 0 },
    totalRevenue: { type: Number, default: 0 },     // Revenue generated by partner
    totalEarnings: { type: Number, default: 0 },    // Commission earned
    pendingPayout: { type: Number, default: 0 },
    lifetimePayout: { type: Number, default: 0 },

    // ─── Assets ────────────────────────────────────────────────────────────
    customAssets: [
      {
        name: String,
        url: String,
        type: { type: String, enum: ['image', 'video', 'document', '3d'] },
        uploadedAt: { type: Date, default: Date.now },
      },
    ],

    // ─── Payout ────────────────────────────────────────────────────────────
    payoutMethod: {
      type: String,
      enum: ['bank_transfer', 'paypal', 'stripe'],
      default: null,
    },
    payoutDetails: {
      type: mongoose.Schema.Types.Mixed,
      select: false,
    },
    nextPayoutDate: { type: Date, default: null },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────
partnerSchema.index({ referralCode: 1 });
partnerSchema.index({ status: 1, tier: 1 });
partnerSchema.index({ user: 1 });

// ─── Pre-save: generate referral code & link ──────────────────────────────────
partnerSchema.pre('save', function (next) {
  if (!this.referralCode) {
    this.referralCode = crypto.randomBytes(5).toString('hex').toUpperCase();
    this.referralLink = `https://velvethusk.com/ref/${this.referralCode}`;
  }
  next();
});

// ─── Virtual: is golden tier eligible ─────────────────────────────────────────
partnerSchema.virtual('isGoldenEligible').get(function () {
  const threshold = parseFloat(process.env.PARTNER_GOLDEN_THRESHOLD || '10000');
  return this.totalRevenue >= threshold;
});

const Partner = mongoose.model('Partner', partnerSchema);
module.exports = Partner;
